documentation:
  - changed-files:
      - any-glob-to-any-file: ['*.md']

descriptors:
  - changed-files:
      - any-glob-to-any-file: ['*/**/*.json']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', '**/*.py', 'Pipfile*']
